name: Update badges

on:
  schedule:
    # Runs at 10:25pm UTC
    - cron: "22 25 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: <ian-allen.902552f3> # optional, but default will use the same from github